-- Tiger Cloud (TimescaleDB) schema for twob-keepers.
--
-- Run this against your Tiger Cloud database before starting `event-keeper`
-- and `read-api`. All tables live in the `public` schema.
--
-- Notes:
-- * `event_time` is the keeper's ingestion timestamp (set per event). It is the
--   bucketing/ordering basis for candles and the hypertable partition column.
-- * Because hypertable unique constraints must include the partition column,
--   dedupe is best-effort on (event_time, event_uid) / (event_time, signature,
--   event_index). The Solana logs subscription does not replay history, so
--   duplicates are rare in practice.
-- * Candle prices are stored as true `numeric` prices. The keeper computes them
--   in SQL by joining `market_configs` for token decimals.

-- ---------------------------------------------------------------------------
-- Market configuration (token decimals / metadata)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS market_configs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id      BIGINT,
    base_mint      TEXT,
    quote_mint     TEXT,
    base_decimals  SMALLINT,
    quote_decimals SMALLINT,
    base_ticker    TEXT,
    quote_ticker   TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS market_configs_market_id_idx
    ON market_configs (market_id);

-- ---------------------------------------------------------------------------
-- Raw market update events
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS raw_market_update_events (
    event_uid   TEXT NOT NULL,
    signature   TEXT NOT NULL,
    event_index INTEGER NOT NULL,
    slot        BIGINT NOT NULL,
    market_id   BIGINT NOT NULL,
    base_flow   BIGINT NOT NULL,
    quote_flow  BIGINT NOT NULL,
    event_time  TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (event_time, event_uid),
    UNIQUE (event_time, signature, event_index)
);
SELECT create_hypertable('raw_market_update_events', 'event_time', if_not_exists => TRUE);
CREATE INDEX IF NOT EXISTS raw_market_update_events_market_time_idx
    ON raw_market_update_events (market_id, event_time DESC);
CREATE INDEX IF NOT EXISTS raw_market_update_events_slot_idx
    ON raw_market_update_events (slot DESC);

-- ---------------------------------------------------------------------------
-- Raw close-position events
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS raw_close_position_events (
    event_uid          TEXT NOT NULL,
    signature          TEXT NOT NULL,
    event_index        INTEGER NOT NULL,
    slot               BIGINT NOT NULL,
    position_authority TEXT NOT NULL,
    market_id          BIGINT NOT NULL,
    start_slot         BIGINT NOT NULL,
    end_slot           BIGINT NOT NULL,
    deposit_amount     BIGINT NOT NULL,
    swapped_amount     BIGINT NOT NULL,
    remaining_amount   BIGINT NOT NULL,
    fee_amount         BIGINT NOT NULL,
    is_buy             BOOLEAN NOT NULL,
    event_time         TIMESTAMPTZ NOT NULL,
    ingested_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (event_time, event_uid),
    UNIQUE (event_time, signature, event_index)
);
SELECT create_hypertable('raw_close_position_events', 'event_time', if_not_exists => TRUE);
CREATE INDEX IF NOT EXISTS raw_close_position_events_authority_time_idx
    ON raw_close_position_events (position_authority, event_time DESC);
CREATE INDEX IF NOT EXISTS raw_close_position_events_market_time_idx
    ON raw_close_position_events (market_id, event_time DESC);
CREATE INDEX IF NOT EXISTS raw_close_position_events_slot_idx
    ON raw_close_position_events (slot DESC);

-- ---------------------------------------------------------------------------
-- 1-minute candles (true OHLC prices). Upserted by the keeper on every market
-- update; the read-api gap-fills empty minutes by carrying the last close.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS market_candles_1m (
    market_id    BIGINT NOT NULL,
    bucket_start TIMESTAMPTZ NOT NULL,
    open         NUMERIC NOT NULL,
    high         NUMERIC NOT NULL,
    low          NUMERIC NOT NULL,
    close        NUMERIC NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (market_id, bucket_start)
);
SELECT create_hypertable('market_candles_1m', 'bucket_start', if_not_exists => TRUE);
CREATE INDEX IF NOT EXISTS market_candles_1m_bucket_start_idx
    ON market_candles_1m (bucket_start DESC);
